/*
 * STACKIT DNS API
 *
 * This api provides dns
 *
 * API version: 1.0
 * Contact: dns@stackit.cloud
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// RecordPost for rr set info.
type RrsetRecordPost struct {
	// content of the record
	Content string `json:"content"`
}
